name: Build image

on:
  # on pull_request does not work with forks since the jobs will try to push
  # to the target registry but run only with the privileges of the fork.
  #- pull_request
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: paulgessinger/docker_cron
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          add_git_labels: true
